// Generated by CoffeeScript 1.3.3
(function() {
  var fs, get_scope, program, repl, request, spawn;

  fs = require('fs');

  program = require('commander');

  spawn = require('child_process').spawn;

  request = require('request');

  repl = require('readline');

  get_scope = function(given) {
    var item, scope, types, _i, _len;
    if ((given != null) && given !== '') {
      return given;
    }
    types = ['content', 'themes', 'products', 'customers', 'orders', 'script_tags', 'shipping'];
    scope = [];
    for (_i = 0, _len = types.length; _i < _len; _i++) {
      item = types[_i];
      scope.push("write_" + item);
    }
    return scope.join(',');
  };

  fs.readFile(__dirname + '/../package.json', function(error, data) {
    var scope, url;
    if (error != null) {
      throw error;
    }
    program.version(JSON.parse(data).version).option('-n --shopname [string]', 'Shopname').option('-i --client_id [string]', 'ClientId').option('-c --scope [string]', 'Scope - Defaults to All').parse(process.argv);
    scope = get_scope(program.scope);
    url = "https://" + program.shopname + ".myshopify.com/admin/oauth/authorize?client_id=" + program.client_id + "&scope=" + scope;
    return console.log(url);
  });

}).call(this);
